# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
      # every 6 hours
    - cron: "0 0 * * 1" # every monday

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: pasheva
          gif_out_path: img/github-contribution-grid-snake.gif
          svg_out_path: img/github-contribution-grid-snake.svg

      - run: git status

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gen-snake
          build_dir: img
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
